
import prisma from '@/lib/prisma'
import { format } from 'date-fns'
import { notFound } from 'next/navigation'
import { TripWithDetails } from '@/types'
import { auth } from "@/auth"
import PrintButton from "@/app/components/PrintButton"

async function getTrip(id: string): Promise<TripWithDetails | null> {
    const trip = await prisma.trip.findUnique({
        where: { id },
        include: {
            days: {
                include: {
                    activities: { orderBy: { order: 'asc' } },
                    highlights: true,
                    accommodation: true,
                },
                orderBy: { dayNumber: 'asc' }
            },
            bookings: true,
        }
    })
    return trip
}

export default async function ShareTripPage({ params }: { params: Promise<{ id: string, locale: string }> }) {
    const { id, locale } = await params;
    const trip = await getTrip(id)
    const session = await auth()

    if (!trip) notFound()

    // Access Control: Public or Owner
    const isOwner = session?.user?.id === trip.userId
    if (!trip.isPublic && !isOwner) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-gray-50">
                <h1 className="text-xl font-bold text-gray-400">This trip is private.</h1>
            </div>
        )
    }

    return (
        <div className="min-h-screen bg-white text-black p-8 max-w-4xl mx-auto print:p-0">
            <div className="flex justify-between items-start mb-8 print:hidden">
                <a href={`/${locale}/trips/${id}`} className="text-indigo-600 hover:underline">← Back to App</a>
                <PrintButton />
            </div>

            <header className="mb-12 border-b-2 border-black pb-4">
                <h1 className="text-5xl font-extrabold mb-2">{trip.title}</h1>
                <p className="text-xl text-gray-600">{trip.subtitle}</p>
                <p className="text-sm mt-2 text-gray-500">
                    {format(new Date(trip.startDate), 'MMM dd, yyyy')} — {format(new Date(trip.endDate), 'MMM dd, yyyy')}
                </p>
            </header>

            <div className="space-y-12">
                {trip.days.map((day: any) => (
                    <section key={day.id} className="break-inside-avoid">
                        <h2 className="text-2xl font-bold mb-4 flex items-center gap-4">
                            <span className="bg-black text-white px-3 py-1 text-lg rounded">Day {day.dayNumber}</span>
                            <span>{day.title}</span>
                            <span className="text-sm font-normal text-gray-500 ml-auto">{format(new Date(day.date), 'EEEE, MMM dd')}</span>
                        </h2>

                        <div className="pl-4 border-l-2 border-gray-200 ml-4 space-y-4">
                            {day.activities.map((act: any) => (
                                <div key={act.id}>
                                    <div className="font-bold text-lg">{act.description}</div>
                                </div>
                            ))}
                        </div>

                        {day.accommodation && (
                            <div className="mt-4 ml-8 bg-gray-50 p-4 rounded border border-gray-200">
                                <strong>🏨 Accommodation:</strong> {day.accommodation.name}
                                <div className="text-sm text-gray-600">{day.accommodation.address}</div>
                            </div>
                        )}
                    </section>
                ))}
            </div>

            <footer className="mt-16 text-center text-gray-400 text-sm print:hidden">
                Generated by Trip Planner for Power P
            </footer>
        </div>
    )
}
